name: Run Selenium On GitHub Action

on:
  workflow_dispatch:
    # You can keep this line if you want to run the workflow on schedule
    # schedule:
    #   - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installing necessary packages
        run: |
          pip install requests smtplib firebase-admin

      - name: Running the blynk
        run: python Blynk_RTL.py
